version: '3.5'

services:
  mongodb:
    image: mongo
    container_name: mongodb1
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
        - ./mongodb-data:/data/db
    networks:
        - mongodb_network
    ports:
        - 27017:27017
    healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    container_name: mongo-express1
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_MONGODB_ADMINUSERNAME=root
        - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
        - ME_CONFIG_BASICAUTH_USERNAME=admin
        - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
        - mongodb
    networks:
        - mongodb_network
    ports:
        - 8081:8081
    healthcheck:
        test:  wget --quiet --tries=3 --spider http://admin:admin123@10.10.10.60:8081 || exit 1
    restart: unless-stopped



networks:
  mongodb_network:
    name: mongodb_network
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: